version: '3'
services:
  main_db:
    image: postgres
    container_name: tender_base
    shm_size: 128mb
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    expose:
      - "${POSTGRES_PORT}"
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    command: -p ${POSTGRES_PORT}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - /private/var/lib/db_cdr:/var/lib/postgresql
      - db:/data/postgres
    restart: unless-stopped
    networks:
      - db_net
volumes:
  db:
networks:
  db_net:
    driver: bridge
