version: '3'
services:
  main_db:
    image: postgres
    container_name: tenderbase
    shm_size: 128mb
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 8181
      POSTGRES_PASSWORD: avppass
      POSTGRES_USER: avpuser
      POSTGRES_DATABASE: postgres
    expose:
      - "${POSTGRES_PORT}"
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    command: -p ${POSTGRES_PORT}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    networks:
      - db_net

  go:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: goAPIs
    depends_on:
      - main_db
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - db_net

networks:
  db_net:
    driver: bridge
